
const ADD_TO_CART = 'ADD_TO_CART';
const LOAD_PRODUCT = 'LOAD_PRODUCT';
const ADD_TODO = 'ADD_TODO';
const SET_TODO = 'SET_TODO';
const LOAD_CARDS = 'LOAD_CARTS';
export { ADD_TO_CART, LOAD_PRODUCT, ADD_TODO, SET_TODO, LOAD_CARDS };
